
    create table credit (
        credit_value numeric(38,2) not null,
        day_first_installment date not null,
        number_of_installments integer not null,
        status tinyint check (status between 0 and 2),
        customer_id bigint,
        id bigint generated by default as identity,
        credit_code uuid not null unique,
        primary key (id)
    );

    create table customers (
        id bigint generated by default as identity,
        cpf varchar(255) not null unique,
        email varchar(255) not null unique,
        first_name varchar(255) not null,
        last_name varchar(255) not null,
        password varchar(255) not null,
        zip_code varchar(255) not null,
        street varchar(255) not null,
        income numeric(38,2) not null,
        primary key (id)
    );

    alter table if exists credit 
       add constraint FKln1q2fd6gno6x9xn78ixt6s2y 
       foreign key (customer_id) 
       references customers;
